using System.Diagnostics;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace ModernFileCleaner.Services;

public class LicenseService
{
    private const string LicenseFile = "license.key";
    private const string TrialFile = "trial.dat";
    private const int TrialDays = 30;

    // RSA 2048-bit public key for license signature verification
    // Generated by KeyGenerator tool - keep private.key secret!
    private static readonly byte[] RsaPublicKey = Convert.FromBase64String(
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1XpxMlWPUPhWmb49MVXl" +
        "6Y0mLll4F5EVbnXOGn8V8YiuqiRDsTbm1pTBQZfSLtleWyM3CCsr1/SGuZYn9J5M" +
        "zDGB6+AFvEfJ1yU/efQLszprBrfMxaq8vp/zfEQEMbl6L1t3x6N+aT8bo8ebVHHg" +
        "lvPiqkRyhdEZ+1CE8Fnvk/SqfEYa3lM1K3epbu67yYZGP7BSOgOQqRL5HJULHex3" +
        "3Fhp7qL8MpP8ijlnrecFDs03V6VO2uEAG8b9hwtWVBmoMbjkrq5XpbgHXkMDYgmg" +
        "MNx2k8EWcXLT5+2FpcPjUVkf9eDgvLk6Gl/AFMOVQHYEq0ckSIU7w5XYQlpBEFAX" +
        "0QIDAQAB");

    public enum LicenseStatus
    {
        Activated,
        Trial,
        Expired,
        Invalid,
        Tampered
    }

    public LicenseStatus Status { get; private set; } = LicenseStatus.Trial;
    public string? LicensedTo { get; private set; }
    public int TrialDaysRemaining { get; private set; } = TrialDays;
    public DateTime? ExpiryDate { get; private set; }

    public LicenseService()
    {
        LoadLicense();
    }

    public string GetMachineFingerprint()
    {
        try
        {
            var parts = new List<string>();
            using var mc = new System.Management.ManagementClass("Win32_Processor");
            using var items = mc.GetInstances();
            foreach (var item in items) { parts.Add(item["ProcessorId"]?.ToString() ?? ""); break; }

            using var mb = new System.Management.ManagementClass("Win32_BaseBoard");
            using var mbItems = mb.GetInstances();
            foreach (var item in mbItems) { parts.Add(item["SerialNumber"]?.ToString() ?? ""); break; }

            using var net = new System.Management.ManagementClass("Win32_NetworkAdapterConfiguration");
            using var netItems = net.GetInstances();
            foreach (var item in netItems)
            {
                var mac = item["MacAddress"]?.ToString();
                if (!string.IsNullOrEmpty(mac) && mac != "00:00:00:00:00:00") { parts.Add(mac); break; }
            }

            var raw = string.Join("-", parts.Where(p => !string.IsNullOrEmpty(p)));
            return BitConverter.ToString(SHA256.HashData(Encoding.UTF8.GetBytes(raw))).Replace("-", "");
        }
        catch { return "UNKNOWN-" + Guid.NewGuid().ToString()[..8]; }
    }

    public bool ValidateLicenseKey(string licenseKey)
    {
        if (string.IsNullOrWhiteSpace(licenseKey))
            return false;

        try
        {
            // Decode Base64 license payload
            var data = licenseKey.Trim().Replace("-", "").Replace(" ", "");
            var bytes = Convert.FromBase64String(data);
            var decoded = Encoding.UTF8.GetString(bytes);

            // Format: signature|machineFP|username|expiry
            var parts = decoded.Split('|');
            if (parts.Length < 4) return false;

            var signatureB64 = parts[0];
            var machineFp = parts[1];
            var userName = parts[2];
            var expiryStr = parts[3];

            // Verify machine binding
            var currentFp = GetMachineFingerprint();
            if (machineFp != currentFp)
            {
                // Allow partial match for minor HW changes
                if (!currentFp.StartsWith(machineFp[..Math.Min(16, machineFp.Length)]))
                    return false;
            }

            // Verify RSA signature
            var payload = $"{machineFp}|{userName}|{expiryStr}";
            var payloadBytes = Encoding.UTF8.GetBytes(payload);
            var signatureBytes = Convert.FromBase64String(signatureB64);

            using var rsa = RSA.Create();
            rsa.ImportSubjectPublicKeyInfo(RsaPublicKey, out _);
            if (!rsa.VerifyData(payloadBytes, signatureBytes, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1))
                return false;

            // Parse expiry
            if (DateTime.TryParse(expiryStr, out var expiry))
            {
                if (expiry < DateTime.UtcNow)
                    return false; // Expired
                ExpiryDate = expiry;
            }

            // All checks passed
            LicensedTo = string.IsNullOrEmpty(userName) || userName == "0" ? "Licensed User" : userName;
            SaveLicense(decoded);
            Status = LicenseStatus.Activated;
            return true;
        }
        catch
        {
            return false;
        }
    }

    private void SaveLicense(string licData)
    {
        try
        {
            var protected_data = ProtectData($"LICENSE:{licData}:{GetMachineFingerprint()}");
            File.WriteAllText(LicenseFile, protected_data);
            // Delete trial file once activated
            if (File.Exists(TrialFile)) File.Delete(TrialFile);
        }
        catch { }
    }

    private void LoadLicense()
    {
        try
        {
            // Check trial
            if (File.Exists(TrialFile))
            {
                var trialData = UnprotectData(File.ReadAllText(TrialFile));
                if (DateTime.TryParse(trialData, out var firstRun))
                {
                    var daysUsed = (DateTime.Now - firstRun).Days;
                    TrialDaysRemaining = Math.Max(0, TrialDays - daysUsed);
                    Status = TrialDaysRemaining <= 0 ? LicenseStatus.Expired : LicenseStatus.Trial;
                    return;
                }
            }

            // First run - start trial
            var data = ProtectData(DateTime.Now.ToString("O"));
            File.WriteAllText(TrialFile, data);
            TrialDaysRemaining = TrialDays;
            Status = LicenseStatus.Trial;

            // Check existing license (overrides trial)
            if (File.Exists(LicenseFile))
            {
                var licData = UnprotectData(File.ReadAllText(LicenseFile));
                if (licData.StartsWith("LICENSE:"))
                {
                    var licParts = licData.Split(':');
                    if (licParts.Length >= 3 && licParts[2] == GetMachineFingerprint())
                    {
                        // Re-verify the stored license signature
                        var storedLic = licParts[1];
                        if (VerifyStoredLicense(storedLic))
                        {
                            Status = LicenseStatus.Activated;
                            LicensedTo = "Licensed User";
                        }
                    }
                }
            }
        }
        catch
        {
            Status = LicenseStatus.Trial;
            TrialDaysRemaining = TrialDays;
        }
    }

    private bool VerifyStoredLicense(string licData)
    {
        try
        {
            var parts = licData.Split('|');
            if (parts.Length < 4) return false;
            var payload = $"{parts[1]}|{parts[2]}|{parts[3]}";
            var payloadBytes = Encoding.UTF8.GetBytes(payload);
            var signatureBytes = Convert.FromBase64String(parts[0]);
            using var rsa = RSA.Create();
            rsa.ImportSubjectPublicKeyInfo(RsaPublicKey, out _);
            return rsa.VerifyData(payloadBytes, signatureBytes, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
        }
        catch { return false; }
    }

    private static string ProtectData(string data)
    {
        try
        {
            var bytes = Encoding.UTF8.GetBytes(data);
            var encrypted = ProtectedData.Protect(bytes, null, DataProtectionScope.CurrentUser);
            return Convert.ToBase64String(encrypted);
        }
        catch { return Convert.ToBase64String(Encoding.UTF8.GetBytes(data)); }
    }

    private static string UnprotectData(string data)
    {
        try
        {
            var encrypted = Convert.FromBase64String(data);
            var decrypted = ProtectedData.Unprotect(encrypted, null, DataProtectionScope.CurrentUser);
            return Encoding.UTF8.GetString(decrypted);
        }
        catch
        {
            try { return Encoding.UTF8.GetString(Convert.FromBase64String(data)); }
            catch { return ""; }
        }
    }

    public void ResetTrial()
    {
        try { if (File.Exists(TrialFile)) File.Delete(TrialFile); } catch { }
        try { if (File.Exists(LicenseFile)) File.Delete(LicenseFile); } catch { }
        Status = LicenseStatus.Trial;
        TrialDaysRemaining = TrialDays;
        LicensedTo = null;
    }
}
